# Game setup
WIDTH = 1280
HEIGHT = 720
FPS = 60

# UI
BAR_HEIGHT = 20
HEALTH_BAR_WIDTH = 200
ENERGY_BAR_WIDTH = 140
BAR_BORDER_WIDTH = 3
ITEM_BOX_SIZE = 80
UI_FONT = 'graphics/font/joystix.ttf'
UI_FONT_SIZE = 18
UI_BORDER_WIDTH = 3


# General colours
UI_BG_COLOUR = '#17223a'
UI_BORDER_COLOUR = '#111111'
TEXT_COLOUR = '#EEEEEE'

# UI colours
HEALTH_COLOUR = 'red'
ENERGY_COLOUR = 'blue'
UI_BORDER_COLOUR_ACTIVE = 'gold'

# Upgrade menu
TEXT_COLOUR_SELECTED = '#111111'
BAR_COLOUR = '#EEEEEE'
BAR_COLOUR_SELECTED = '#111111'
UPGRADE_BG_COLOUR_SELECTED = '#EEEEEE'
UPGRADE_BORDER_WIDTH = 4

# Runner Player Defaults
RUNNER_START_CLICKS = 4
RUNNER_START_CREDITS = 5
RUNNER_START_DECK_SIZE = 0
RUNNER_START_HAND_SIZE = 5

# Corp Player Defaults
CORP_START_CLICKS = 3
CORP_START_CREDITS = 5
CORP_START_DECK_SIZE = 0
CORP_START_HAND_SIZE = 5

# Card Colours
HAASBIROID_BACKGROUND = '#111111'
